[project]
name = "nre-city"
version = "1.0.0"
description = "This script processes input data about actions diricted to cities in NRE and outputs changes based on provided data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
